version: "3.7"

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wp-content/:/var/www/html/wp-content/
      - ./src/:/var/www/html/wp-content/themes/src/
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "true"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/var/lib/mysql/
