version: '3.7'

services:
  wordpress:
    build: ./containers/wordpress
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
    volumes:
      # - wp_data:/var/www/html/wp-content
      - ./wp_data/:/var/www/html/wp-content
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  # wp_data:
  db_data:
